### ISSUE TITLE
Provide a better way to select a specific choice when member modification is not needed

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/snappi#38]
```python
import snappi
api = snappi.api()
config = api.config()

f, = config.flows.flow(name='f1')

# we want flow duration to use fixed packets
# 1st approach
f.duration.fixed_packets
# 2nd approach
f.duration.choice = f.duration.FIXED_PACKETS

print(config)
```

Output for 1st approach:
```yaml
flows:
- duration:
    fixed_packets:
      delay: null
      delay_unit: null
      gap: null
      packets: null
  name: f1
```

Output for 2nd approach:
```yaml
flows:
- duration:
    choice: fixed_packets
  name: f1
```

Proposed approach:

```python
import snappi
api = snappi.api()
config = api.config()

f, = config.flows.flow(name='f1')

# we want flow duration to use fixed packets
# output 1
f.duration.fixed_packets.defaults()

# output 2
f.duration.fixed_packets
print(config)

# output 3
f.duration.choice = f.duration.FIXED_PACKETS
print(config)
```

Output:
```yaml
# output 1
flows:
- duration:
    choice: fixed_packets
    fixed_packets:
      delay: null
      delay_unit: null
      gap: null
      packets: null
  name: f1

# output 2
flows:
- duration:
    choice: fixed_packets
  name: f1

# output 3
flows:
- duration:
    choice: fixed_packets
  name: f1
```
